
package publicadores;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;
import util.ConfigLoader;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
public class PublicadorEventoService
    extends Service
{

    private final static URL PUBLICADOREVENTOSERVICE_WSDL_LOCATION;
    private final static WebServiceException PUBLICADOREVENTOSERVICE_EXCEPTION;
    private final static QName PUBLICADOREVENTOSERVICE_QNAME = new QName("http://publicadores/", "PublicadorEventoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
        	   String ip = ConfigLoader.get("ipServidor");
           	   String puerto = ConfigLoader.get("puerto");
           	   url = new URL("http://" + ip + ":" + puerto + "/publicadorEvento?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PUBLICADOREVENTOSERVICE_WSDL_LOCATION = url;
        PUBLICADOREVENTOSERVICE_EXCEPTION = e;
    }

    public PublicadorEventoService() {
        super(__getWsdlLocation(), PUBLICADOREVENTOSERVICE_QNAME);
    }

    public PublicadorEventoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PUBLICADOREVENTOSERVICE_QNAME, features);
    }

    public PublicadorEventoService(URL wsdlLocation) {
        super(wsdlLocation, PUBLICADOREVENTOSERVICE_QNAME);
    }

    public PublicadorEventoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PUBLICADOREVENTOSERVICE_QNAME, features);
    }

    public PublicadorEventoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PublicadorEventoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PublicadorEvento
     */
    @WebEndpoint(name = "PublicadorEventoPort")
    public PublicadorEvento getPublicadorEventoPort() {
        return super.getPort(new QName("http://publicadores/", "PublicadorEventoPort"), PublicadorEvento.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PublicadorEvento
     */
    @WebEndpoint(name = "PublicadorEventoPort")
    public PublicadorEvento getPublicadorEventoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicadores/", "PublicadorEventoPort"), PublicadorEvento.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PUBLICADOREVENTOSERVICE_EXCEPTION!= null) {
            throw PUBLICADOREVENTOSERVICE_EXCEPTION;
        }
        return PUBLICADOREVENTOSERVICE_WSDL_LOCATION;
    }

}
