
package publicadores;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;
import util.ConfigLoader;



/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
public class PublicadorEstadisticasService
    extends Service
{

    private final static URL PUBLICADORESTADISTICASSERVICE_WSDL_LOCATION;
    private final static WebServiceException PUBLICADORESTADISTICASSERVICE_EXCEPTION;
    private final static QName PUBLICADORESTADISTICASSERVICE_QNAME = new QName("http://publicadores/", "PublicadorEstadisticasService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
       	   String ip = ConfigLoader.get("ipServidor");
       	   String puerto = ConfigLoader.get("puerto");
       	   url = new URL("http://" + ip + ":" + puerto + "/publicadorEstadisticas?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PUBLICADORESTADISTICASSERVICE_WSDL_LOCATION = url;
        PUBLICADORESTADISTICASSERVICE_EXCEPTION = e;
    }

    public PublicadorEstadisticasService() {
        super(__getWsdlLocation(), PUBLICADORESTADISTICASSERVICE_QNAME);
    }

    public PublicadorEstadisticasService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PUBLICADORESTADISTICASSERVICE_QNAME, features);
    }

    public PublicadorEstadisticasService(URL wsdlLocation) {
        super(wsdlLocation, PUBLICADORESTADISTICASSERVICE_QNAME);
    }

    public PublicadorEstadisticasService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PUBLICADORESTADISTICASSERVICE_QNAME, features);
    }

    public PublicadorEstadisticasService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PublicadorEstadisticasService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PublicadorEstadisticas
     */
    @WebEndpoint(name = "PublicadorEstadisticasPort")
    public PublicadorEstadisticas getPublicadorEstadisticasPort() {
        return super.getPort(new QName("http://publicadores/", "PublicadorEstadisticasPort"), PublicadorEstadisticas.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PublicadorEstadisticas
     */
    @WebEndpoint(name = "PublicadorEstadisticasPort")
    public PublicadorEstadisticas getPublicadorEstadisticasPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicadores/", "PublicadorEstadisticasPort"), PublicadorEstadisticas.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PUBLICADORESTADISTICASSERVICE_EXCEPTION!= null) {
            throw PUBLICADORESTADISTICASSERVICE_EXCEPTION;
        }
        return PUBLICADORESTADISTICASSERVICE_WSDL_LOCATION;
    }

}
