
package publicadores;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "TipoRegistroYaExisteException", targetNamespace = "http://publicadores/")
public class TipoRegistroYaExisteException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private TipoRegistroYaExisteException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public TipoRegistroYaExisteException_Exception(String message, TipoRegistroYaExisteException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public TipoRegistroYaExisteException_Exception(String message, TipoRegistroYaExisteException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: publicadores.TipoRegistroYaExisteException
     */
    public TipoRegistroYaExisteException getFaultInfo() {
        return faultInfo;
    }

}
