
package publicadores;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "CostoTipoRegistroInvalidoException", targetNamespace = "http://publicadores/")
public class CostoTipoRegistroInvalidoException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CostoTipoRegistroInvalidoException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CostoTipoRegistroInvalidoException_Exception(String message, CostoTipoRegistroInvalidoException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public CostoTipoRegistroInvalidoException_Exception(String message, CostoTipoRegistroInvalidoException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: publicadores.CostoTipoRegistroInvalidoException
     */
    public CostoTipoRegistroInvalidoException getFaultInfo() {
        return faultInfo;
    }

}
