
package publicadores;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "PublicadorEstadisticas", targetNamespace = "http://publicadores/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PublicadorEstadisticas {


    /**
     * 
     * @param n
     * @return
     *     returns publicadores.DtTopEventoArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorEstadisticas/topEventosRequest", output = "http://publicadores/PublicadorEstadisticas/topEventosResponse")
    public DtTopEventoArray topEventos(
        @WebParam(name = "n", partName = "n")
        int n);

    /**
     * 
     * @param eventoNombre
     */
    @WebMethod
    @Action(input = "http://publicadores/PublicadorEstadisticas/registrarVisitaRequest", output = "http://publicadores/PublicadorEstadisticas/registrarVisitaResponse")
    public void registrarVisita(
        @WebParam(name = "eventoNombre", partName = "eventoNombre")
        String eventoNombre);

    /**
     * 
     */
    @WebMethod
    @Action(input = "http://publicadores/PublicadorEstadisticas/resetVisitasRequest", output = "http://publicadores/PublicadorEstadisticas/resetVisitasResponse")
    public void resetVisitas();

    /**
     * 
     * @param cantidad
     * @param eventoNombre
     */
    @WebMethod
    @Action(input = "http://publicadores/PublicadorEstadisticas/setVisitasEventoRequest", output = "http://publicadores/PublicadorEstadisticas/setVisitasEventoResponse")
    public void setVisitasEvento(
        @WebParam(name = "eventoNombre", partName = "eventoNombre")
        String eventoNombre,
        @WebParam(name = "cantidad", partName = "cantidad")
        int cantidad);

}
