
package publicadores;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "PublicadorUsuario", targetNamespace = "http://publicadores/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PublicadorUsuario {


    /**
     * 
     * @param identificador
     * @return
     *     returns publicadores.DtRegistro
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorUsuario/obtenerDatosRegistrosRequest", output = "http://publicadores/PublicadorUsuario/obtenerDatosRegistrosResponse")
    public DtRegistro obtenerDatosRegistros(
        @WebParam(name = "identificador", partName = "identificador")
        String identificador);

    /**
     * 
     * @param apellido
     * @param descripcion
     * @param fechaNacimiento
     * @param imagen
     * @param institucion
     * @param link
     * @param nickname
     * @param nombre
     * @throws UsuarioNoExisteException_Exception
     * @throws UsuarioTipoIncorrectoException_Exception
     */
    @WebMethod
    @Action(input = "http://publicadores/PublicadorUsuario/modificarDatosUsuarioRequest", output = "http://publicadores/PublicadorUsuario/modificarDatosUsuarioResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://publicadores/PublicadorUsuario/modificarDatosUsuario/Fault/UsuarioNoExisteException"),
        @FaultAction(className = UsuarioTipoIncorrectoException_Exception.class, value = "http://publicadores/PublicadorUsuario/modificarDatosUsuario/Fault/UsuarioTipoIncorrectoException")
    })
    public void modificarDatosUsuario(
        @WebParam(name = "nickname", partName = "nickname")
        String nickname,
        @WebParam(name = "nombre", partName = "nombre")
        String nombre,
        @WebParam(name = "descripcion", partName = "descripcion")
        String descripcion,
        @WebParam(name = "link", partName = "link")
        String link,
        @WebParam(name = "apellido", partName = "apellido")
        String apellido,
        @WebParam(name = "fechaNacimiento", partName = "fechaNacimiento")
        String fechaNacimiento,
        @WebParam(name = "institucion", partName = "institucion")
        String institucion,
        @WebParam(name = "imagen", partName = "imagen")
        String imagen)
        throws UsuarioNoExisteException_Exception, UsuarioTipoIncorrectoException_Exception
    ;

    /**
     * 
     * @param nickname
     * @return
     *     returns publicadores.DtDatosUsuario
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorUsuario/obtenerDatosUsuarioRequest", output = "http://publicadores/PublicadorUsuario/obtenerDatosUsuarioResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://publicadores/PublicadorUsuario/obtenerDatosUsuario/Fault/UsuarioNoExisteException")
    })
    public DtDatosUsuario obtenerDatosUsuario(
        @WebParam(name = "nickname", partName = "nickname")
        String nickname)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @return
     *     returns publicadores.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorUsuario/listarInstitucionesRequest", output = "http://publicadores/PublicadorUsuario/listarInstitucionesResponse")
    public StringArray listarInstituciones();

    /**
     * 
     * @param nickname
     * @param nuevaContrasenia
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @Action(input = "http://publicadores/PublicadorUsuario/modificarContraseniaRequest", output = "http://publicadores/PublicadorUsuario/modificarContraseniaResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://publicadores/PublicadorUsuario/modificarContrasenia/Fault/UsuarioNoExisteException")
    })
    public void modificarContrasenia(
        @WebParam(name = "nickname", partName = "nickname")
        String nickname,
        @WebParam(name = "nuevaContrasenia", partName = "nuevaContrasenia")
        String nuevaContrasenia)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param nombre
     * @throws CategoriaYaExisteException_Exception
     */
    @WebMethod
    @Action(input = "http://publicadores/PublicadorUsuario/altaCategoriaSinGUIRequest", output = "http://publicadores/PublicadorUsuario/altaCategoriaSinGUIResponse", fault = {
        @FaultAction(className = CategoriaYaExisteException_Exception.class, value = "http://publicadores/PublicadorUsuario/altaCategoriaSinGUI/Fault/CategoriaYaExisteException")
    })
    public void altaCategoriaSinGUI(
        @WebParam(name = "nombre", partName = "nombre")
        String nombre)
        throws CategoriaYaExisteException_Exception
    ;

    /**
     * 
     * @param seguido
     * @param seguidor
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorUsuario/sigueARequest", output = "http://publicadores/PublicadorUsuario/sigueAResponse")
    public boolean sigueA(
        @WebParam(name = "seguidor", partName = "seguidor")
        String seguidor,
        @WebParam(name = "seguido", partName = "seguido")
        String seguido);

    /**
     * 
     * @param apellido
     * @param contrasena
     * @param correo
     * @param descripcion
     * @param esOrganizador
     * @param fechaNacimientoISO
     * @param imagen
     * @param institucion
     * @param link
     * @param nickname
     * @param nombre
     * @throws UsuarioYaExisteException_Exception
     */
    @WebMethod
    @Action(input = "http://publicadores/PublicadorUsuario/altaUsuarioRequest", output = "http://publicadores/PublicadorUsuario/altaUsuarioResponse", fault = {
        @FaultAction(className = UsuarioYaExisteException_Exception.class, value = "http://publicadores/PublicadorUsuario/altaUsuario/Fault/UsuarioYaExisteException")
    })
    public void altaUsuario(
        @WebParam(name = "nickname", partName = "nickname")
        String nickname,
        @WebParam(name = "nombre", partName = "nombre")
        String nombre,
        @WebParam(name = "correo", partName = "correo")
        String correo,
        @WebParam(name = "descripcion", partName = "descripcion")
        String descripcion,
        @WebParam(name = "link", partName = "link")
        String link,
        @WebParam(name = "apellido", partName = "apellido")
        String apellido,
        @WebParam(name = "fechaNacimientoISO", partName = "fechaNacimientoISO")
        String fechaNacimientoISO,
        @WebParam(name = "institucion", partName = "institucion")
        String institucion,
        @WebParam(name = "esOrganizador", partName = "esOrganizador")
        boolean esOrganizador,
        @WebParam(name = "contrasena", partName = "contrasena")
        String contrasena,
        @WebParam(name = "imagen", partName = "imagen")
        String imagen)
        throws UsuarioYaExisteException_Exception
    ;

    /**
     * 
     * @return
     *     returns publicadores.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorUsuario/getInstitucionesRequest", output = "http://publicadores/PublicadorUsuario/getInstitucionesResponse")
    public StringArray getInstituciones();

    /**
     * 
     * @param nickname
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorUsuario/esAsistenteRequest", output = "http://publicadores/PublicadorUsuario/esAsistenteResponse")
    public boolean esAsistente(
        @WebParam(name = "nickname", partName = "nickname")
        String nickname);

    /**
     * 
     * @param seguido
     * @param seguidor
     */
    @WebMethod
    @Action(input = "http://publicadores/PublicadorUsuario/dejarSeguirUsuarioRequest", output = "http://publicadores/PublicadorUsuario/dejarSeguirUsuarioResponse")
    public void dejarSeguirUsuario(
        @WebParam(name = "seguidor", partName = "seguidor")
        String seguidor,
        @WebParam(name = "seguido", partName = "seguido")
        String seguido);

    /**
     * 
     * @param nickname
     * @param registroId
     * @throws UsuarioNoExisteException_Exception
     * @throws UsuarioTipoIncorrectoException_Exception
     */
    @WebMethod
    @Action(input = "http://publicadores/PublicadorUsuario/marcarAsistenciaRequest", output = "http://publicadores/PublicadorUsuario/marcarAsistenciaResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://publicadores/PublicadorUsuario/marcarAsistencia/Fault/UsuarioNoExisteException"),
        @FaultAction(className = UsuarioTipoIncorrectoException_Exception.class, value = "http://publicadores/PublicadorUsuario/marcarAsistencia/Fault/UsuarioTipoIncorrectoException")
    })
    public void marcarAsistencia(
        @WebParam(name = "nickname", partName = "nickname")
        String nickname,
        @WebParam(name = "registroId", partName = "registroId")
        String registroId)
        throws UsuarioNoExisteException_Exception, UsuarioTipoIncorrectoException_Exception
    ;

    /**
     * 
     * @return
     *     returns publicadores.DtDatosUsuarioArray
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorUsuario/obtenerUsuariosDTRequest", output = "http://publicadores/PublicadorUsuario/obtenerUsuariosDTResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://publicadores/PublicadorUsuario/obtenerUsuariosDT/Fault/UsuarioNoExisteException")
    })
    public DtDatosUsuarioArray obtenerUsuariosDT()
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param seguido
     * @param seguidor
     */
    @WebMethod
    @Action(input = "http://publicadores/PublicadorUsuario/seguirUsuarioRequest", output = "http://publicadores/PublicadorUsuario/seguirUsuarioResponse")
    public void seguirUsuario(
        @WebParam(name = "seguidor", partName = "seguidor")
        String seguidor,
        @WebParam(name = "seguido", partName = "seguido")
        String seguido);

    /**
     * 
     * @param contrasena
     * @param nickOrEmail
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PublicadorUsuario/validarLoginRequest", output = "http://publicadores/PublicadorUsuario/validarLoginResponse")
    public boolean validarLogin(
        @WebParam(name = "nickOrEmail", partName = "nickOrEmail")
        String nickOrEmail,
        @WebParam(name = "contrasena", partName = "contrasena")
        String contrasena);

    /**
     * 
     * @param descripcion
     * @param link
     * @param nombre
     * @throws InstitucionYaExisteException_Exception
     */
    @WebMethod
    @Action(input = "http://publicadores/PublicadorUsuario/altaInstitucionRequest", output = "http://publicadores/PublicadorUsuario/altaInstitucionResponse", fault = {
        @FaultAction(className = InstitucionYaExisteException_Exception.class, value = "http://publicadores/PublicadorUsuario/altaInstitucion/Fault/InstitucionYaExisteException")
    })
    public void altaInstitucion(
        @WebParam(name = "nombre", partName = "nombre")
        String nombre,
        @WebParam(name = "descripcion", partName = "descripcion")
        String descripcion,
        @WebParam(name = "link", partName = "link")
        String link)
        throws InstitucionYaExisteException_Exception
    ;

}
